import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// Imported 
import { Toaster } from "@/provider/toaster"
import { ThemeProvider } from "@/provider/theme"
import Navbar from '@/components/navbar/Navbar'
import getuser from '@/lib/getuser'
import UseStoreInitializer from '@/components/navbar/storeuser'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let user = await getuser();
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {
          user ? (
            <UseStoreInitializer name={user.name} email={user.email} image={user.image} createdAt={user.createdAt} updatedAt={user.updatedAt} mobile_number={user.mobile_number} isauthenticated={user.isauthenticated} />
          ) : (
            <UseStoreInitializer name='' email='' image='' mobile_number='' isauthenticated={false} createdAt={new Date} updatedAt={new Date} />
          )
        }
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
